# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dcfrontend.ui'
#
# Created: Fri Nov 19 10:16:45 2010
#      by: PyQt4 UI code generator 4.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_DC_control(object):
    def setupUi(self, DC_control):
        DC_control.setObjectName(_fromUtf8("DC_control"))
        DC_control.setEnabled(True)
        DC_control.resize(596, 176)
        font = QtGui.QFont()
        font.setUnderline(False)
        DC_control.setFont(font)
        self.label = QtGui.QLabel(DC_control)
        self.label.setGeometry(QtCore.QRect(30, 50, 56, 15))
        self.label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label.setWordWrap(False)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(DC_control)
        self.label_2.setGeometry(QtCore.QRect(480, 50, 56, 15))
        self.label_2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lcdBlue = QtGui.QLCDNumber(DC_control)
        self.lcdBlue.setGeometry(QtCore.QRect(10, 70, 81, 71))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.lcdBlue.setFont(font)
        self.lcdBlue.setAutoFillBackground(False)
        self.lcdBlue.setFrameShadow(QtGui.QFrame.Plain)
        self.lcdBlue.setSmallDecimalPoint(False)
        self.lcdBlue.setNumDigits(3)
        self.lcdBlue.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdBlue.setObjectName(_fromUtf8("lcdBlue"))
        self.verticalLayoutWidget = QtGui.QWidget(DC_control)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(100, 100, 301, 51))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.labelTilt = QtGui.QLabel(self.verticalLayoutWidget)
        self.labelTilt.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTilt.setObjectName(_fromUtf8("labelTilt"))
        self.verticalLayout.addWidget(self.labelTilt)
        self.sliderTilt = QtGui.QSlider(self.verticalLayoutWidget)
        self.sliderTilt.setOrientation(QtCore.Qt.Horizontal)
        self.sliderTilt.setObjectName(_fromUtf8("sliderTilt"))
        self.verticalLayout.addWidget(self.sliderTilt)
        self.verticalLayoutWidget_2 = QtGui.QWidget(DC_control)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(100, 50, 301, 51))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.labelLevel = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.labelLevel.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLevel.setObjectName(_fromUtf8("labelLevel"))
        self.verticalLayout_2.addWidget(self.labelLevel)
        self.sliderLevel = QtGui.QSlider(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        self.sliderLevel.setFont(font)
        self.sliderLevel.setOrientation(QtCore.Qt.Horizontal)
        self.sliderLevel.setObjectName(_fromUtf8("sliderLevel"))
        self.verticalLayout_2.addWidget(self.sliderLevel)
        self.spinLevel = QtGui.QSpinBox(DC_control)
        self.spinLevel.setGeometry(QtCore.QRect(400, 50, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.spinLevel.setFont(font)
        self.spinLevel.setObjectName(_fromUtf8("spinLevel"))
        self.spinTilt = QtGui.QSpinBox(DC_control)
        self.spinTilt.setGeometry(QtCore.QRect(400, 100, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.spinTilt.setFont(font)
        self.spinTilt.setObjectName(_fromUtf8("spinTilt"))
        self.lcdRed = QtGui.QLCDNumber(DC_control)
        self.lcdRed.setGeometry(QtCore.QRect(470, 70, 81, 71))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.lcdRed.setFont(font)
        self.lcdRed.setAutoFillBackground(False)
        self.lcdRed.setFrameShadow(QtGui.QFrame.Plain)
        self.lcdRed.setSmallDecimalPoint(False)
        self.lcdRed.setNumDigits(3)
        self.lcdRed.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdRed.setObjectName(_fromUtf8("lcdRed"))
        self.title = QtGui.QLabel(DC_control)
        self.title.setGeometry(QtCore.QRect(160, 10, 231, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(12)
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.title.setFont(font)
        self.title.setTextFormat(QtCore.Qt.AutoText)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName(_fromUtf8("title"))

        self.retranslateUi(DC_control)
        QtCore.QMetaObject.connectSlotsByName(DC_control)

    def retranslateUi(self, DC_control):
        DC_control.setWindowTitle(QtGui.QApplication.translate("DC_control", "DC control", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DC_control", "Blue", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DC_control", "Red", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTilt.setText(QtGui.QApplication.translate("DC_control", "Tilt", None, QtGui.QApplication.UnicodeUTF8))
        self.labelLevel.setText(QtGui.QApplication.translate("DC_control", "Level", None, QtGui.QApplication.UnicodeUTF8))
        self.title.setText(QtGui.QApplication.translate("DC_control", "DC Endcaps", None, QtGui.QApplication.UnicodeUTF8))

